export const ADD_SINGLE_TODO = 'ADD_SINGLE_TODO';
export const TOGGLE_COMPLETE_TODO = 'TOGGLE_COMPLETE_TODO';
export const FILTER_TODS_LIST = 'FILTER_TODS_LIST';
export const DELETE_TODO = 'DELETE_TODO';


export const Filters = {
    ALL_TODOS: 'ALL_TODOS',
    ACTIVE_TODOS: 'ACTIVE_TODOS',
    COMPLETE_TODOS: 'COMPLETE_TODOS'
};